#ifndef LOADINGDIALOGGLOBAL_H
#define LOADINGDIALOGGLOBAL_H
#include <QtCore/qglobal.h>

#if defined(LOADINGDIALOG_LIBRARY)
#  define LOADINGDIALOGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LOADINGDIALOGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LOADINGDIALOGGLOBAL_H
